parameters:
#    example_api.example.class: Example\Bundle\ApiBundle\Example

services:
#    example_api.example:
#        class: %example_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
